### ISSUE TITLE
Multiple Audio Inputs

### ISSUE THREAD

**Issue by ataylor-orcsd-org** [ElectronicTheatreControlsLabs/Sound2Light#10]
Is it possible to handle multiple audio inputs?  Either stereo, or let's say several solo mics directly into the system?

**Comment by luminosuslight** [comment]
No, it's not possible to use multiple audio inputs with Sound2Light.
But you can use [Luminosus](https://www.luminosus.org) for this instead. It provides all the functionality of the Sound2Light Tool as blocks and it is possible to set a different audio input for each one.
